# -*- coding: utf-8 -*-
"""helloworld_github.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C-TVPTXGI5Q59MjXJcxizM5KVzPoCSbN
"""

print("Hello World!")